### ISSUE TITLE
Bug: Footer prop has typescript error after updating from latest v7 to v8

### ISSUE THREAD

**Issue by Blumed** [gpbl/react-day-picker#1423]
DayPicker version:
React version:

Using the new footer prop I am getting a typescript error

```
No overload matches this call.
  Overload 1 of 2, '(props: DayPickerProps | Readonly<DayPickerProps>): DayPicker', gave the following error.
    Type '{ onDayClick: (day: Date) => void; firstDayOfWeek: number; footer: any; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<DayPicker> & Readonly<DayPickerProps> & Readonly<...>'.
      Property 'footer' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<DayPicker> & Readonly<DayPickerProps> & Readonly<...>'.
  Overload 2 of 2, '(props: DayPickerProps, context: any): DayPicker', gave the following error.
    Type '{ onDayClick: (day: Date) => void; firstDayOfWeek: number; footer: any; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<DayPicker> & Readonly<DayPickerProps> & Readonly<...>'.
      Property 'footer' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<DayPicker> & Readonly<DayPickerProps> & Readonly<...>'.ts(2769)
```

### To reproduce

Code sandbox: https://codesandbox.io/s/react-day-picker-8-vl4ry <- I tried to use this but the sandbox is borked with the following error `Could not fetch dependencies, please try again in a couple seconds: Cannot read properties of null (reading 'match')`

#### Steps

1. Start a project using v7.4.10
2. yarn upgrade
3. Everything renders fine. I was only using `onDayClick` and `firstDayOfWeek` props so nothing needed to be converted
4. add the footer prop and boom typescript error

### Expected behavior

There isn't a typescript error and I am able to use the footer prop as intended

### Screenshots

![Screen Shot 2022-03-31 at 10 17 51 PM](https://user-images.githubusercontent.com/2773888/161188707-8f257fce-0e72-4823-8a2a-4ea46ebafd0e.png)

**Comment by Blumed** [comment]
I fixed it. I removed `@types/react-day-picker` and instead of `yarn upgrade` I ran `yarn add` and it is all working fine now.

**Comment by gpbl** [comment]
@Blumed thanks for your report! We'll add the note to the upgrade guide!
