### PR TITLE
fix(types): update type export to allow importing DateUtils methods

### PR DESCRIPTION
**Pull request by Nibblesh**
👋🏽 Thanks for opening a pull request!

Issues: https://github.com/gpbl/react-day-picker/issues/865, https://github.com/gpbl/react-day-picker/issues/887, https://github.com/gpbl/react-day-picker/pull/896

Explicitly list module declaration for exported util functions

* Please explain clearly your changes. If they involve a lot of code, let discuss them first in on our gitter room: 
https://gitter.im/gpbl/react-day-picker
* 🙏🏽 Please **DO NOT** build files or update the docs in your pull request – as this may cause git conflicts. Thanks!

### CODE REVIEW

**Comment by veddermatic** [comment]
Any ideas when this will get merged / published?

**Comment by gpbl** [comment]
Here we go, sorry – i've been too busy lately.

**Comment by milesj** [comment]
@Nibblesh @gpbl This doesn't seem to work on TS v3.5.

```
node_modules/react-day-picker/types/index.d.ts:10:35 - error TS2694: Namespace '"node_modules/react-day-picker/types/utils"' has no exported member 'DateUtils'.

10 export const DateUtils: UtilTypes.DateUtils;
                                     ~~~~~~~~~

node_modules/react-day-picker/types/index.d.ts:11:37 - error TS2694: Namespace '"node_modules/react-day-picker/types/utils"' has no exported member 'LocaleUtils'.

11 export const LocaleUtils: UtilTypes.LocaleUtils;
                                       ~~~~~~~~~~~

node_modules/react-day-picker/types/index.d.ts:12:40 - error TS2694: Namespace '"node_modules/react-day-picker/types/utils"' has no exported member 'ModifiersUtils'.

12 export const ModifiersUtils: UtilTypes.ModifiersUtils;
                                          ~~~~~~~~~~~~~~
```

**Comment by rhfung** [comment]
Same here, doesn't seem to work on TS v3.5

**Comment by Nibblesh** [comment]
Was going to give this a try today but it seems to have been fixed:
https://github.com/gpbl/react-day-picker/pull/916
